### PR TITLE
mounting es data as volume

### PR DESCRIPTION
**Pull request by ciklista**

### CODE REVIEW

**Comment by ciklista** [comment]
I think volumes is the easier solution or is there a case where we want the data to be easily accessible from the host?

**Comment by Trolldemorted** [comment]
Our usecase is "It is 3am, @ldruschk wants to shut down the VM and we want to get the data to a safe location" 😇

**Comment by ciklista** [comment]
Then we might need to do a proper backup of the data. 
https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshot-restore.html
Also with reference to the warning on there :D

**Comment by Trolldemorted** [comment]
Is the warning relevant to us if we turn the elastic off before copying? "Elasticsearch may be making changes to the contents of its data directories while it is running" is true during runtime, but offline migrations shouldn't be an issue (?)

**Pull request merged**
